### ISSUE TITLE
give the descirption for the repo ('about'), please

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_gists#2]

**Comment by ildarkhasanshin** [comment]
не понял про какое описание идет речь?
install.inf -> info -> desc не то?

**Comment by ildarkhasanshin** [comment]
![image](https://user-images.githubusercontent.com/8765305/162604418-56d8a724-bf91-4bcd-b029-789199e1a2a4.png)

это описание откуда подтягиевается?
в конце вместо git д.б. gist

**Comment by Alexey-T** [comment]
ops, fixed.

**Comment by Alexey-T** [comment]
про описание репозитория в сайте ГХ.

**Comment by ildarkhasanshin** [comment]
в [README.md](https://github.com/ildarkhasanshin/cuda_gists/blob/master/README.md) ведь

**Comment by Alexey-T** [comment]
вот оно
![de](https://user-images.githubusercontent.com/4154978/162607290-b0eb79fe-e794-4da8-9105-e10b6c0966a7.png)

**Comment by ildarkhasanshin** [comment]
добавил
