### ISSUE TITLE
better use msg_status instead of msg_box

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_gists#7]
```
     if len(gists) == 100:
                    ii = ii + 1
            else:
                msg_box('Empty response!', MB_OK)
```
and maybe not only here

**Comment by ildarkhasanshin** [comment]
imho, сообщение в msg_status малозаметно

**Comment by Alexey-T** [comment]
1. MB_ICONnnn should be added to MB_OK

2. make nice message in msgbox: like "GitHub Gist: empty responce"

**Comment by ildarkhasanshin** [comment]
https://github.com/ildarkhasanshin/cuda_gists/commit/aecca5ba8f0e6e22541c6789b6ac90c7c78d671f
